/**
 * Every family in the Google Fonts directory.
 *
 * Generated by `scripts/gen-google-fonts.mjs` from fonts.google.com's own
 * metadata — do not edit by hand. Each line is
 *
 *     name|category|weights|italic weights|axes
 *
 * with weights written as one digit per hundred (`4` is 400, `a` is 1000) and
 * each axis as `tag min max default`. Families are in popularity order, which
 * is the order the picker's "Popular fonts" filter shows them in.
 */

/** What the variable-axis sliders are labelled, by tag. */
export const AXIS_NAMES: Record<string, string> = {
  "JITT": "Jitter",
  "ARRR": "AR Retinal Resolution",
  "BLED": "Bleed",
  "BNCE": "Bounce",
  "CASL": "Casual",
  "CRSV": "Cursive",
  "CTRS": "Contrast",
  "EDPT": "Extrusion Depth",
  "EHLT": "Edge Highlight",
  "ELGR": "Element Grid",
  "ELSH": "Element Shape",
  "ELXP": "Element Expansion",
  "ENLA": "Enlarge",
  "FILL": "Fill",
  "FLAR": "Flare",
  "GDOP": "Guides Opacity",
  "GEOM": "Geometric Form",
  "GRAD": "Grade",
  "HEXP": "Hyper Expansion",
  "INFM": "Informality",
  "MONO": "Monospace",
  "MORF": "Morph",
  "ROND": "Roundness",
  "SCAN": "Scanlines",
  "SHLN": "Shadow Length",
  "SHRP": "Sharpness",
  "SOFT": "Softness",
  "SPAC": "Spacing",
  "SZP1": "Size of Paint 1",
  "SZP2": "Size of Paint 2",
  "VOLM": "Volume",
  "WONK": "Wonky",
  "XELA": "Horizontal Element Alignment",
  "XOPQ": "Thick Stroke",
  "XPN1": "Horizontal Position of Paint 1",
  "XPN2": "Horizontal Position of Paint 2",
  "XROT": "Rotation in X",
  "XTRA": "Counter Width",
  "YEAR": "Year",
  "YELA": "Vertical Element Alignment",
  "YEXT": "Vertical Extension",
  "YOPQ": "Thin Stroke",
  "YPN1": "Vertical Position of Paint 1",
  "YPN2": "Vertical Position of Paint 2",
  "YROT": "Rotation in Y",
  "YTAS": "Ascender Height",
  "YTDE": "Descender Depth",
  "YTFI": "Figure Height",
  "YTLC": "Lowercase Height",
  "YTUC": "Uppercase Height",
  "ZROT": "Rotation in Z",
  "ital": "Italic",
  "opsz": "Optical Size",
  "slnt": "Slant",
  "wdth": "Width",
  "wght": "Weight"
};

export const GOOGLE_FONT_DATA = `\
Open Sans|s|345678|345678|wdth 75 100 100;wght 300 800 400
Roboto|s|123456789|123456789|wdth 75 100 100;wght 100 900 400
Google Sans|s|4567|4567|GRAD -50 200 0;opsz 17 18 18;wght 400 700 400
Inter|s|123456789|123456789|opsz 14 32 14;wght 100 900 400
Montserrat|s|123456789|123456789|wght 100 900 400
Poppins|s|123456789|123456789|
Noto Sans JP|s|123456789||wght 100 900 400
Lato|s|13479|13479|
Arimo|s|4567|4567|wght 400 700 400
Roboto Condensed|s|123456789|123456789|wght 100 900 400
Roboto Mono|m|1234567|1234567|wght 100 700 400
Oswald|s|234567||wght 200 700 400
Noto Sans|s|123456789|123456789|wdth 62.5 100 100;wght 100 900 400
DM Sans|s|123456789a|a123456789|opsz 9 40 14;wght 100 1000 400
Raleway|s|123456789|123456789|wght 100 900 400
Nunito|s|23456789a|a23456789|wght 200 1000 400
Nunito Sans|s|23456789a|a23456789|YTLC 440 540 500;opsz 6 12 12;wdth 75 125 100;wght 200 1000 400
Playfair Display|f|456789|456789|wght 400 900 400
Roboto Slab|f|123456789||wght 100 900 400
Rubik|s|3456789|3456789|wght 300 900 400
Ubuntu|s|3457|3457|
Manrope|s|2345678||wght 200 800 400
Kanit|s|123456789|123456789|
Archivo Black|s|4||
Outfit|s|123456789||wght 100 900 400
Merriweather|f|3456789|3456789|opsz 18 144 18;wdth 87 112 100;wght 300 900 400
Noto Sans KR|s|123456789||wght 100 900 400
Work Sans|s|123456789|123456789|wght 100 900 400
Lora|f|4567|4567|wght 400 700 400
PT Sans|s|47|47|
Quicksand|s|34567||wght 300 700 400
Noto Sans TC|s|123456789||wght 100 900 400
Figtree|s|3456789|3456789|wght 300 900 400
Bebas Neue|s|4||
Plus Jakarta Sans|s|2345678|2345678|wght 200 800 400
Mulish|s|23456789a|a23456789|wght 200 1000 400
Barlow|s|123456789|123456789|
Source Sans 3|s|23456789|23456789|wght 200 900 400
Prompt|s|123456789|123456789|
Bricolage Grotesque|s|2345678||opsz 12 96 14;wdth 75 100 100;wght 200 800 400
IBM Plex Sans|s|1234567|1234567|wdth 75 100 100;wght 100 700 400
Jost|s|123456789|123456789|wght 100 900 400
Saira|s|123456789|123456789|wdth 50 125 100;wght 100 900 400
Karla|s|2345678|2345678|wght 200 800 400
Black Ops One|d|4||
Archivo|s|123456789|123456789|wdth 62 125 100;wght 100 900 400
JetBrains Mono|m|12345678|12345678|wght 100 800 400
Inconsolata|m|23456789||wdth 50 200 100;wght 200 900 400
Source Code Pro|m|23456789|23456789|wght 200 900 400
Fira Sans|s|123456789|123456789|
Share Tech|s|4||
Smooch Sans|s|123456789||wght 100 900 400
Noto Serif|f|123456789|123456789|wdth 62.5 100 100;wght 100 900 400
Titillium Web|s|234679|23467|
Space Grotesk|s|34567||wght 300 700 400
Libre Baskerville|f|4567|4567|wght 400 700 400
Heebo|s|123456789||wght 100 900 400
Cormorant Garamond|f|34567|34567|wght 300 700 400
PT Serif|f|47|47|
Noto Color Emoji|s|4||
Fjalla One|s|4||
Noto Sans SC|s|123456789||wght 100 900 400
Google Sans Flex|s|0.01123456789a||GRAD 0 100 0;ROND 0 100 0;opsz 6 144 18;slnt -10 0 0;wdth 25 151 100;wght 1 1000 400
Libre Franklin|s|123456789|123456789|wght 100 900 400
Dancing Script|h|4567||wght 400 700 400
Lobster Two|d|47|47|
Barlow Condensed|s|123456789|123456789|
Anton|s|4||
Public Sans|s|123456789|123456789|wght 100 900 400
EB Garamond|f|45678|45678|wght 400 800 400
Noto Serif JP|f|23456789||wght 200 900 400
Instrument Serif|f|4|4|
Josefin Sans|s|1234567|1234567|wght 100 700 400
Changa One|d|4|4|
Lexend|s|123456789||wght 100 900 400
Sora|s|12345678||wght 100 800 400
Fraunces|f|123456789|123456789|SOFT 0 100 0;WONK 0 1 0;opsz 9 144 14;wght 100 900 400
IBM Plex Mono|m|1234567|1234567|
Urbanist|s|123456789|123456789|wght 100 900 400
Inter Tight|s|123456789|123456789|wght 100 900 400
Mukta|s|2345678||
Schibsted Grotesk|s|456789|456789|wght 400 900 400
Cairo|s|23456789a||slnt -11 11 0;wght 200 1000 400
Bitter|f|123456789|123456789|wght 100 900 400
Assistant|s|2345678||wght 200 800 400
Cabin|s|4567|4567|wdth 75 100 100;wght 400 700 400
Rajdhani|s|34567||
Roboto Flex|s|123456789a||GRAD -200 150 0;XOPQ 27 175 96;XTRA 323 603 468;YOPQ 25 135 79;YTAS 649 854 750;YTDE -305 -98 -203;YTFI 560 788 738;YTLC 416 570 514;YTUC 528 760 712;opsz 8 144 14;slnt -10 0 0;wdth 25 151 100;wght 100 1000 400
Nanum Gothic|s|478||
Alfa Slab One|d|4||
Hind Siliguri|s|34567||
DM Serif Display|f|4|4|
Dosis|s|2345678||wght 200 800 400
Lilita One|d|4||
Caveat|h|4567||wght 400 700 400
Red Hat Display|s|3456789|3456789|wght 300 900 400
Exo 2|s|123456789|123456789|wght 100 900 400
Noto Sans Khmer|s|123456789||wdth 62.5 100 100;wght 100 900 400
Geist|s|123456789|123456789|wght 100 900 400
Orbitron|s|456789||wght 400 900 400
Oxygen|s|347||
Cinzel|f|456789||wght 400 900 400
Overpass|s|123456789|123456789|wght 100 900 400
Noto Sans Telugu|s|123456789||wdth 62.5 100 100;wght 100 900 400
Hind|s|34567||
Fredoka|s|34567||wdth 75 125 100;wght 300 700 400
Source Serif 4|f|23456789|23456789|opsz 8 60 14;wght 200 900 400
M PLUS Rounded 1c|s|1345789||
Crimson Text|f|467|467|
Ramabhadra|s|4||
Anek Telugu|s|12345678||wdth 75 125 100;wght 100 800 400
Bungee|d|4||
Instrument Sans|s|4567|4567|wdth 75 100 100;wght 400 700 400
M PLUS 1p|s|1345789||
Pacifico|h|4||
Tajawal|s|2345789||
PT Sans Narrow|s|47||
Hanken Grotesk|s|123456789|123456789|wght 100 900 400
Slabo 27px|f|4||
Barlow Semi Condensed|s|123456789|123456789|
Lobster|d|4||
Merriweather Sans|s|345678|345678|wght 300 800 400
Domine|f|4567||wght 400 700 400
Gravitas One|d|4||
Arvo|f|47|47|
Teko|s|34567||wght 300 700 400
League Spartan|s|123456789||wght 100 900 400
Noto Sans Arabic|s|123456789||wdth 62.5 100 100;wght 100 900 400
Comfortaa|d|34567||wght 300 700 400
Abel|s|4||
Noto Sans Thai|s|123456789||wdth 62.5 100 100;wght 100 900 400
Abril Fatface|d|4||
Newsreader|f|2345678|2345678|opsz 6 72 16;wght 200 800 400
Asap|s|123456789|123456789|wdth 75 125 100;wght 100 900 400
Zeyada|h|4||
Maven Pro|s|456789||wght 400 900 400
Bodoni Moda|f|456789|456789|opsz 6 96 11;wght 400 900 400
Shadows Into Light|h|4||
ABeeZee|s|4|4|
Zilla Slab|f|34567|34567|
Questrial|s|4||
DM Mono|m|345|345|
Space Mono|m|47|47|
Satisfy|h|4||
Rethink Sans|s|45678|45678|wght 400 800 400
Varela Round|s|4||
Geist Mono|m|123456789|123456789|wght 100 900 400
Lexend Deca|s|123456789||wght 100 900 400
Albert Sans|s|123456789|123456789|wght 100 900 400
Archivo Narrow|s|4567|4567|wght 400 700 400
Chakra Petch|s|34567|34567|
Zen Kaku Gothic New|s|34579||
Play|s|47||
Sofia Sans|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Exo|s|123456789|123456789|wght 100 900 400
Alumni Sans|s|123456789|123456789|wght 100 900 400
Onest|s|123456789||wght 100 900 400
Be Vietnam Pro|s|123456789|123456789|
Almarai|s|3478||
IBM Plex Serif|f|1234567|1234567|
Marcellus|f|4||
Great Vibes|h|4||
Spectral|f|2345678|2345678|
Indie Flower|h|4||
Unbounded|s|23456789||wght 200 900 400
Cormorant|f|34567|34567|wght 300 700 400
Syne|s|45678||wght 400 800 400
Permanent Marker|h|4||
Roboto Serif|f|123456789|123456789|GRAD -50 100 0;opsz 8 144 14;wdth 50 150 100;wght 100 900 400
Red Hat Text|s|34567|34567|wght 300 700 400
Frank Ruhl Libre|f|3456789||wght 300 900 400
Yanone Kaffeesatz|s|234567||wght 200 700 400
Epilogue|s|123456789|123456789|wght 100 900 400
Crimson Pro|f|23456789|23456789|wght 200 900 400
Noto Sans Tamil|s|123456789||wdth 62.5 100 100;wght 100 900 400
Sanchez|f|4|4|
Geologica|s|123456789||CRSV 0 1 0;SHRP 0 100 0;slnt -12 0 0;wght 100 900 400
Nanum Myeongjo|f|478||
Saira Condensed|s|123456789||
IBM Plex Sans Arabic|s|1234567||
Titan One|d|4||
Vollkorn|f|456789|456789|wght 400 900 400
Oleo Script|d|47||
Noto Serif KR|f|23456789||wght 200 900 400
Noto Serif TC|f|23456789||wght 200 900 400
Noto Serif SC|f|23456789||wght 200 900 400
Baloo 2|d|45678||wght 400 800 400
Kalam|h|347||
Zen Maru Gothic|s|34579||
Sarabun|s|12345678|12345678|
Amiri|f|47|47|
Literata|f|23456789|23456789|opsz 7 72 14;wght 200 900 400
Fira Sans Condensed|s|123456789|123456789|
Alegreya Sans|s|1345789|1345789|
Courier Prime|m|47|47|
Russo One|s|4||
Encode Sans|s|123456789||wdth 75 125 100;wght 100 900 400
Catamaran|s|123456789||wght 100 900 400
Signika|s|34567||GRAD -30 0 0;wght 300 700 400
Delius|h|4||
Atkinson Hyperlegible|s|47|47|
Luckiest Guy|d|4||
Fira Code|m|34567||wght 300 700 400
Andada Pro|f|45678|45678|wght 400 840 400
Rowdies|d|347||
Cardo|f|47|4|
Press Start 2P|d|4||
Noto Sans Display|s|123456789|123456789|wdth 62.5 100 100;wght 100 900 400
Prata|f|4||
Creepster|d|4||
Righteous|d|4||
Viga|s|4||
Bree Serif|f|4||
Chivo|s|123456789|123456789|wght 100 900 400
Antic Slab|f|4||
DM Serif Text|f|4|4|
Montserrat Alternates|s|123456789|123456789|
Noto Kufi Arabic|s|123456789||wght 100 900 400
Noto Nastaliq Urdu|f|4567||wght 400 700 400
News Cycle|s|47||
Baskervville|f|4567|4567|wght 400 700 400
Playfair|f|3456789|3456789|opsz 5 1200 14;wdth 87.5 112.5 100;wght 300 900 400
Aleo|f|123456789|123456789|wght 100 900 400
Hammersmith One|s|4||
Acme|s|4||
Libre Barcode 39|d|4||
Readex Pro|s|234567||HEXP 0 100 0;wght 160 700 400
Yellowtail|h|4||
LINE Seed JP|s|1478||
Noto Naskh Arabic|f|4567||wght 400 700 400
IBM Plex Sans Condensed|s|1234567|1234567|
Paytone One|s|4||
Tinos|f|47|47|
Noto Sans Devanagari|s|123456789||wdth 62.5 100 100;wght 100 900 400
Kumbh Sans|s|123456789||YOPQ 40 300 300;wght 100 900 400
Shippori Mincho|f|45678||
Gothic A1|s|123456789||
Amatic SC|h|47||
Special Elite|d|4||
Alegreya|f|456789|456789|wght 400 900 400
Fugaz One|d|4||
Alata|s|4||
Tenor Sans|s|4||
Khand|s|34567||
Changa|s|2345678||wght 200 800 400
Patua One|d|4||
Bangers|d|4||
Old Standard TT|f|47|4|
Share Tech Mono|m|4||
Kaushan Script|h|4||
Martel|f|2346789||
M PLUS U|s|123456789||wght 100 900 400
Allura|h|4||
Advent Pro|s|123456789|123456789|wdth 100 200 100;wght 100 900 400
Hind Madurai|s|34567||
Golos Text|s|456789||wght 400 900 400
Nanum Gothic Coding|h|47||
Cantarell|s|47|47|
Sacramento|h|4||
VT323|m|4||
Sawarabi Mincho|f|4||
Courgette|h|4||
Libre Caslon Text|f|47|4|
Noticia Text|f|47|47|
Crete Round|f|4|4|
Patrick Hand|h|4||
Chelsea Market|d|4||
Comic Neue|h|347|347|
Noto Sans Mono|s|123456789||wdth 62.5 100 100;wght 100 900 400
PT Sans Caption|s|47||
Sen|s|45678||wght 400 800 400
Oxanium|d|2345678||wght 200 800 400
Sawarabi Gothic|s|4||
BIZ UDPGothic|s|47||
Francois One|s|4||
Lexend Giga|s|123456789||wght 100 900 400
Antonio|s|1234567||wght 100 700 400
Asap Condensed|s|23456789|23456789|
Angkor|d|4||
Cookie|h|4||
Passion One|d|479||
Rokkitt|f|123456789|123456789|wght 100 900 400
Sofia Sans Condensed|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Quattrocento|f|47||
Gruppo|s|4||
Zen Old Mincho|f|45679||
PT Mono|m|4||
Philosopher|s|47|47|
Audiowide|d|4||
STIX Two Text|f|4567|4567|wght 400 700 400
Gloria Hallelujah|h|4||
Josefin Slab|f|1234567|1234567|wght 100 700 400
Italianno|h|4||
Yantramanav|s|134579||
Didact Gothic|s|4||
Commissioner|s|123456789||FLAR 0 100 0;VOLM 0 100 0;slnt -12 0 0;wght 100 900 400
League Gothic|s|4||wdth 75 100 100
Google Sans Code|m|345678|345678|MONO 0 1 1;wght 300 800 400
Actor|s|4||
Alexandria|s|123456789||wght 100 900 400
Quattrocento Sans|s|47|47|
Eczar|f|45678||wght 400 800 400
Neuton|f|23478|4|
Biryani|s|2346789||
Quantico|s|47|47|
Architects Daughter|h|4||
M PLUS 1|s|123456789||wght 100 900 400
Rubik Mono One|s|4||
Signika Negative|s|34567||wght 300 700 400
Gilda Display|f|4||
Encode Sans Condensed|s|123456789||
Cinzel Decorative|d|479||
Krub|s|234567|234567|
Ubuntu Condensed|s|4||
Bai Jamjuree|s|234567|234567|
Radio Canada|s|34567|34567|wdth 75 100 100;wght 300 700 400
Rock Salt|h|4||
Lustria|f|4||
Playfair Display SC|f|479|479|
Noto Sans Bengali|s|123456789||wdth 62.5 100 100;wght 100 900 400
Jura|s|34567||wght 300 700 400
Kosugi Maru|s|4||
Tangerine|h|47||
Unna|f|47|47|
Vazirmatn|s|123456789||wght 100 900 400
Alex Brush|h|4||
Forum|d|4||
Dela Gothic One|d|4||
Homemade Apple|h|4||
Noto Serif Display|f|123456789|123456789|wdth 62.5 100 100;wght 100 900 400
Istok Web|s|47|47|
Faustina|f|345678|345678|wght 300 800 400
Pathway Gothic One|s|4||
Poiret One|d|4||
Amaranth|s|47|47|
Concert One|d|4||
Abhaya Libre|f|45678||
Noto Sans HK|s|123456789||wght 100 900 400
Gabarito|d|456789||wght 400 900 400
Caveat Brush|h|4||
Yeseva One|d|4||
Playball|d|4||
Chango|d|4||
Rammetto One|d|4||
Pinyon Script|h|4||
Noto Sans Hebrew|s|123456789||wdth 62.5 100 100;wght 100 900 400
El Messiri|s|4567||wght 400 700 400
Monoton|d|4||
Noto Sans Symbols|s|123456789||wght 100 900 400
Unica One|d|4||
Monda|s|4567||wght 400 700 400
Cutive Mono|m|4||
Damion|h|4||
Berkshire Swash|h|4||
Black Han Sans|s|4||
Eater|d|4||
Gelasio|f|4567|4567|wght 400 700 400
GFS Didot|f|4||
Staatliches|d|4||
Libre Bodoni|f|4567|4567|wght 400 700 400
Lusitana|f|47||
Nothing You Could Do|h|4||
Lalezar|s|4||
Reenie Beanie|h|4||
Ubuntu Mono|m|47|47|
Nanum Pen Script|h|4||
Arsenal|s|47|47|
Parisienne|h|4||
Petrona|f|123456789|123456789|wght 100 900 400
Blinker|s|12346789||
Sorts Mill Goudy|f|4|4|
Mitr|s|234567||
Cormorant Infant|f|34567|34567|wght 300 700 400
Merienda|h|3456789||wght 300 900 400
Saira Extra Condensed|s|123456789||
Anonymous Pro|m|47|47|
Goldman|d|47||
Hind Guntur|s|34567||
Michroma|s|4||
Andika|s|47|47|
Vidaloka|f|4||
Racing Sans One|d|4||
Besley|f|456789|456789|wght 400 900 400
Georama|s|123456789|123456789|wdth 62.5 150 100;wght 100 900 400
Belleza|s|4||
Radio Canada Big|s|4567|4567|wght 400 700 400
Ubuntu Sans|s|12345678|12345678|wdth 75 100 100;wght 100 800 400
Ropa Sans|s|4|4|
Volkhov|f|47|47|
IBM Plex Sans Thai|s|1234567||
Cousine|m|47|47|
Ms Madi|h|4||
Cuprum|s|4567|4567|wght 400 700 400
Secular One|s|4||
Host Grotesk|s|345678|345678|wght 300 800 400
Dongle|s|347||
Anek Bangla|s|12345678||wdth 75 125 100;wght 100 800 400
Syncopate|s|47||
Noto Sans Malayalam|s|123456789||wdth 62.5 100 100;wght 100 900 400
Sriracha|h|4||
Bad Script|h|4||
Hind Vadodara|s|34567||
Fira Sans Extra Condensed|s|123456789|123456789|
Mr Dafoe|h|4||
Mukta Malar|s|2345678||
Caprasimo|d|4||
Fira Mono|m|457||
Carter One|d|4||
Palanquin Dark|s|4567||
Mona Sans|s|23456789|23456789|wdth 75 125 100;wght 200 900 400
Jua|s|4||
Handlee|h|4||
Gochi Hand|h|4||
Palanquin|s|1234567||
Sofia|h|4||
Afacad|s|4567|4567|wght 400 700 400
Noto Serif Bengali|f|123456789||wdth 62.5 100 100;wght 100 900 400
Six Caps|s|4||
Arapey|f|4|4|
Averia Serif Libre|d|347|347|
Alice|f|4||
Varela|s|4||
Saira Semi Condensed|s|123456789||
Macondo|d|4||
Sofia Sans Extra Condensed|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Squada One|d|4||
Marck Script|h|4||
Mada|s|23456789||wght 200 900 400
Amita|h|47||
Mrs Saint Delafield|h|4||
Suez One|f|4||
Alegreya Sans SC|s|1345789|1345789|
Ultra|f|4||
Comic Relief|d|47||
Pragati Narrow|s|47||
Cabin Condensed|s|4567||
Calistoga|d|4||
Economica|s|47|47|
Taviraj|f|123456789|123456789|
Zen Kaku Gothic Antique|s|34579||
Wix Madefor Display|s|45678||wght 400 800 400
Gudea|s|47|4|
Covered By Your Grace|h|4||
Julius Sans One|s|4||
Belanosima|s|467||
Shippori Mincho B1|f|45678||
Familjen Grotesk|s|4567|4567|wght 400 700 400
Londrina Solid|d|1349||
Aboreto|d|4||
Bevan|f|4|4|
Reddit Sans|s|23456789|23456789|wght 200 900 400
Grandstander|d|123456789|123456789|wght 100 900 400
Adamina|f|4||
Shrikhand|d|4||
Atkinson Hyperlegible Next|s|2345678|2345678|wght 200 800 400
Parkinsans|s|345678||wght 300 800 400
Pridi|f|234567||
Funnel Sans|s|345678|345678|wght 300 800 400
Mandali|s|4||
Fahkwang|s|234567|234567|
REM|s|123456789|123456789|wght 100 900 400
Chewy|d|4||
Stardos Stencil|d|47||
Pangolin|h|4||
Khula|s|34678||
Mate|f|4|4|
Cedarville Cursive|h|4||
M PLUS 2|s|123456789||wght 100 900 400
Red Hat Mono|m|34567|34567|wght 300 700 400
Geo|s|4|4|
Leckerli One|h|4||
Electrolize|s|4||
Italiana|s|4||
IBM Plex Sans JP|s|1234567||
Skranji|d|47||
Martel Sans|s|2346789||
Wix Madefor Text|s|45678|45678|wght 400 800 400
Aldrich|s|4||
Bowlby One SC|d|4||
Ovo|f|4||
Ma Shan Zheng|h|4||
Darker Grotesque|s|3456789||wght 300 900 400
Niramit|s|234567|234567|
Pirata One|d|4||
La Belle Aurore|h|4||
Vina Sans|d|4||
Kreon|f|34567||wght 300 700 400
Nanum Brush Script|h|4||
Ruda|s|456789||wght 400 900 400
Murecho|s|123456789||wght 100 900 400
Kaisei Decol|f|457||
Boogaloo|d|4||
Limelight|d|4||
Reem Kufi|s|4567||wght 400 700 400
Funnel Display|d|345678||wght 300 800 400
Rye|d|4||
Coda|d|48||
Tilt Warp|d|4||XROT -45 45 0;YROT -45 45 0
Fustat|s|2345678||wght 200 800 400
Tomorrow|s|123456789|123456789|
BenchNine|s|347||
Inria Serif|f|347|347|
Lemonada|d|34567||wght 300 700 400
Gantari|s|123456789|123456789|wght 100 900 400
IM Fell English|f|4|4|
Do Hyeon|s|4||
Itim|h|4||
Carlito|s|47|47|
Herr Von Muellerhoff|h|4||
Rufina|f|47||
Charm|h|47||
Germania One|d|4||
Gowun Batang|f|47||
Spinnaker|s|4||
Proza Libre|s|45678|45678|
Anek Devanagari|s|12345678||wdth 75 125 100;wght 100 800 400
Yrsa|f|34567|34567|wght 300 700 400
Special Gothic Expanded One|s|4||
Neucha|h|4||
Sarala|s|47||
Just Another Hand|h|4||
Basic|s|4||
Hachi Maru Pop|h|4||
Akshar|s|34567||wght 300 700 400
Sansita|s|4789|4789|
Marcellus SC|f|4||
Nixie One|d|4||
Yatra One|d|4||
UnifrakturMaguntia|d|4||
Balsamiq Sans|d|47|47|
Big Shoulders|d|123456789||opsz 10 72 14;wght 100 900 400
Sintony|s|47||
Krona One|s|4||
Potta One|d|4||
Oooh Baby|h|4||
Spline Sans|s|34567||wght 300 700 400
Anuphan|s|1234567||wght 100 700 400
Livvic|s|12345679|12345679|
Noto Sans Sinhala|s|123456789||wdth 62.5 100 100;wght 100 900 400
Glegoo|f|47||
K2D|s|12345678|12345678|
Anek Latin|s|12345678||wdth 75 125 100;wght 100 800 400
Barriecito|d|4||
Bentham|f|4||
Pontano Sans|s|34567||wght 300 700 400
Noto Sans Gujarati|s|123456789||wdth 62.5 100 100;wght 100 900 400
Sofia Sans Semi Condensed|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Days One|s|4||
Judson|f|47|4|
Gloock|f|4||
Elsie|d|49||
Shadows Into Light Two|h|4||
Libre Barcode 128|d|4||
Kiwi Maru|f|345||
Baloo Da 2|d|45678||wght 400 800 400
Cabin Sketch|d|47||
Jersey 25|d|4||
Caudex|f|47|47|
Castoro|f|4|4|
Kameron|f|4567||wght 400 700 400
Overpass Mono|m|34567||wght 300 700 400
Mali|h|234567|234567|
ZCOOL XiaoWei|s|4||
Corben|d|47||
Aclonica|s|4||
Annie Use Your Telescope|h|4||
Rozha One|f|4||
Pixelify Sans|d|4567||wght 400 700 400
MuseoModerno|d|123456789|123456789|wght 100 900 400
Averia Libre|d|347|347|
Glory|s|12345678|12345678|wght 100 800 400
Libre Caslon Display|f|4||
BIZ UDGothic|s|47||
Graduate|f|4||
Karma|f|34567||
Bowlby One|d|4||
Azeret Mono|m|123456789|123456789|wght 100 900 400
PT Serif Caption|f|4|4|
Yuji Mai|f|4||
Encode Sans Expanded|s|123456789||
Fragment Mono|m|4|4|
Podkova|f|45678||wght 400 800 400
Radley|f|4|4|
Grenze Gotisch|d|123456789||wght 100 900 400
Bellefair|f|4||
Tiro Bangla|f|4|4|
Fredericka the Great|d|4||
Armata|s|4||
Noto Sans Gurmukhi|s|123456789||wdth 62.5 100 100;wght 100 900 400
TikTok Sans|s|3456789||opsz 12 36 14;slnt -6 0 0;wdth 75 150 100;wght 300 900 400
Oranienbaum|f|4||
Bona Nova SC|f|47|4|
Hepta Slab|f|0.01123456789||wght 1 900 400
Cantata One|f|4||
Niconne|h|4||
Style Script|h|4||
Allison|h|4||
Candal|s|4||
Petit Formal Script|h|4||
Nobile|s|457|457|
Athiti|s|234567||
IBM Plex Sans KR|s|1234567||
Trirong|f|123456789|123456789|
Noto Sans Meetei Mayek|s|123456789||wght 100 900 400
Arbutus Slab|f|4||
Ibarra Real Nova|f|4567|4567|wght 400 700 400
Tektur|d|456789||wdth 75 100 100;wght 400 900 400
Cormorant Upright|f|34567||
Trocchi|f|4||
Metrophobic|s|4||
DotGothic16|s|4||
Noto Sans Kannada|s|123456789||wdth 62.5 100 100;wght 100 900 400
Lateef|f|2345678||
Cormorant SC|f|34567||
Gabriela|f|4||
Charis SIL|f|47|47|
Afacad Flux|s|123456789a||slnt -14 14 0;wght 100 1000 400
Lexend Exa|s|123456789||wght 100 900 400
Enriqueta|f|4567||
Dawning of a New Day|h|4||
Antic Didone|f|4||
Goudy Bookletter 1911|f|4||
Seaweed Script|d|4||
Laila|f|34567||
Norican|h|4||
Koulen|d|4||
Pathway Extreme|s|123456789|123456789|opsz 8 144 12;wdth 75 100 100;wght 100 900 400
Protest Revolution|d|4||
Chonburi|d|4||
AR One Sans|s|4567||ARRR 10 60 10;wght 400 700 400
Schoolbell|h|4||
Rancho|h|4||
ZCOOL KuaiLe|s|4||
Share|s|47|47|
Chivo Mono|m|123456789|123456789|wght 100 900 400
Grand Hotel|h|4||
Allerta Stencil|s|4||
Alef|s|47||
Brygada 1918|f|4567|4567|wght 400 700 400
Playpen Sans|h|12345678||wght 100 800 400
Knewave|d|4||
Wallpoet|d|4||
Spline Sans Mono|m|34567|34567|wght 300 700 400
BIZ UDPMincho|f|47||
Pattaya|s|4||
Zen Antique|f|4||
Silkscreen|d|47||
DynaPuff|d|4567||wdth 75 100 100;wght 400 700 400
Marmelad|s|4||
ADLaM Display|d|4||
Noto Serif Georgian|f|123456789||wdth 62.5 100 100;wght 100 900 400
Markazi Text|f|4567||wght 400 700 400
Caladea|f|47|47|
Fondamento|h|4|4|
Arizonia|h|4||
Klee One|h|46||
Yesteryear|h|4||
Telex|s|4||
Bayon|s|4||
Montagu Slab|f|1234567||opsz 16 144 144;wght 100 700 400
IM Fell English SC|f|4||
Alegreya SC|f|45789|45789|
Nova Square|d|4||
Quintessential|h|4||
Fjord One|f|4||
Kosugi|s|4||
Marvel|s|47|47|
Tiro Devanagari Hindi|f|4|4|
Ephesis|h|4||
MedievalSharp|d|4||
Cal Sans|s|4||
Mochiy Pop One|s|4||
Noto Sans Georgian|s|123456789||wdth 62.5 100 100;wght 100 900 400
Sniglet|d|48||
Average Sans|s|4||
Inria Sans|s|347|347|
Rakkas|d|4||
Coustard|f|49||
Hina Mincho|f|4||
Halant|f|34567||
Young Serif|f|4||
BioRhyme|f|2345678||wdth 100 125 100;wght 200 800 400
Kristi|h|4||
Noto Sans Myanmar|s|123456789||wdth 62.5 100 100;wght 100 900 400
Rampart One|d|4||
Mouse Memoirs|s|4||
Irish Grover|d|4||
Yusei Magic|s|4||
Allerta|s|4||
Reddit Sans Condensed|s|23456789||wght 200 900 400
Flow Circular|d|4||
Cormorant Unicase|f|34567||
Rosario|s|34567|34567|wght 300 700 400
Copse|f|4||
Coming Soon|h|4||
Lexend Peta|s|123456789||wght 100 900 400
Noto Serif Devanagari|f|123456789||wdth 62.5 100 100;wght 100 900 400
Honk|d|4||MORF 0 45 15;SHLN 0 100 50
Sedgwick Ave Display|h|4||
Qwitcher Grypen|h|47||
Alatsi|s|4||
Hahmlet|f|123456789||wght 100 900 400
Noto Sans Oriya|s|123456789||wdth 62.5 100 100;wght 100 900 400
Bubblegum Sans|d|4||
Calligraffitti|h|4||
Overlock|d|479|479|
Noto Emoji|s|34567||wght 300 700 400
Anybody|d|123456789|123456789|wdth 50 150 100;wght 100 900 400
Lexend Zetta|s|123456789||wght 100 900 400
Fauna One|f|4||
Libre Barcode 39 Text|d|4||
Kelly Slab|d|4||
Recursive|s|3456789a||CASL 0 1 0;CRSV 0 1 0.5;MONO 0 1 0;slnt -15 0 0;wght 300 1000 400
Major Mono Display|m|4||
Corinthia|h|47||
Sigmar One|d|4||
Crafty Girls|h|4||
Monomaniac One|s|4||
Fanwood Text|f|4|4|
Faster One|d|4||
Sometype Mono|m|4567|4567|wght 400 700 400
Vollkorn SC|f|4679||
Amiko|s|467||
Slabo 13px|f|4||
RocknRoll One|s|4||
Scada|s|47|47|
Croissant One|d|4||
Average|f|4||
Over the Rainbow|h|4||
Vujahday Script|h|4||
Hedvig Letters Serif|f|4||opsz 12 24 24
Baloo Thambi 2|d|45678||wght 400 800 400
Love Ya Like A Sister|d|4||
Chiron GoRound TC|s|23456789||wght 200 900 400
Waiting for the Sunrise|h|4||
Rouge Script|h|4||
STIX Two Math|f|4||
Inclusive Sans|s|34567|34567|wght 300 700 400
Farro|s|3457||
Asul|f|47||
Noto Sans Math|s|4||
Mountains of Christmas|d|47||
Kantumruy Pro|s|1234567|1234567|wght 100 700 400
Noto Sans Ol Chiki|s|4567||wght 400 700 400
Zalando Sans|s|23456789|23456789|wdth 75 125 100;wght 200 900 400
Sansita Swashed|d|3456789||wght 300 900 400
IM Fell DW Pica|f|4|4|
Pompiere|d|4||
Monsieur La Doulaise|h|4||
Magra|s|47||
Scheherazade New|f|4567||
Whisper|h|4||
Almendra|f|47|47|
Doppio One|s|4||
Turret Road|d|234578||
Nova Mono|m|4||
Meddon|h|4||
Grape Nuts|h|4||
Brawler|f|47||
Mansalva|h|4||
ZCOOL QingKe HuangYou|s|4||
Poller One|d|4||
Rubik Doodle Shadow|d|4||
Gowun Dodum|s|4||
Inknut Antiqua|f|3456789||
Abyssinica SIL|f|4||
Hanuman|f|123456789||wght 100 900 400
Red Rose|d|34567||wght 300 700 400
Lekton|m|47|4|
Noto Serif Khojki|f|4567||wght 400 700 400
Bellota Text|d|347|347|
Hurricane|h|4||
Syne Mono|m|4||
Maitree|f|234567||
Carrois Gothic|s|4||
Agbalumo|d|4||
Happy Monkey|d|4||
Miriam Libre|s|4567||wght 400 700 400
Beth Ellen|h|4||
Bungee Spice|d|4||
Akatab|s|456789||
Tilt Neon|d|4||XROT -45 45 0;YROT -45 45 0
Anton SC|s|4||
Zalando Sans Expanded|s|23456789|23456789|wght 200 900 400
Original Surfer|d|4||
Poetsen One|d|4||
Shantell Sans|d|345678|345678|BNCE -100 100 0;INFM 0 100 0;SPAC 0 100 0;wght 300 800 400
Oxygen Mono|m|4||
Kadwa|f|47||
Cherry Bomb One|d|4||
Rambla|s|47|47|
Rochester|h|4||
Baloo Bhai 2|d|45678||wght 400 800 400
B612 Mono|m|47|47|
Noto Sans Thai Looped|s|123456789||wdth 62.5 100 100;wght 100 900 400
Libertinus Serif|f|467|467|
Aguafina Script|h|4||
Manjari|s|147||
Yuji Syuku|f|4||
Battambang|d|13479||
Slackey|d|4||
Birthstone|h|4||
Bungee Inline|d|4||
Poly|f|4|4|
Zen Dots|d|4||
Metamorphous|d|4||
Platypi|f|345678|345678|wght 300 800 400
IBM Plex Sans Hebrew|s|1234567||
Gaegu|h|347||
Ruslan Display|d|4||
Xanh Mono|m|4|4|
Noto Sans Warang Citi|s|4||
Boldonse|d|4||
Encode Sans Semi Condensed|s|123456789||
KoHo|s|234567|234567|
Fasthand|d|4||
Qwigley|h|4||
Megrim|d|4||
Sarina|d|4||
Aref Ruqaa|f|47||
Spectral SC|f|2345678|2345678|
Meow Script|h|4||
Voltaire|s|4||
Vampiro One|d|4||
Baloo Bhaijaan 2|d|45678||wght 400 800 400
Jersey 10|d|4||
Cairo Play|s|23456789a||slnt -11 11 0;wght 200 1000 400
Rubik Dirt|d|4||
Frijole|d|4||
Mukta Mahee|s|2345678||
Lacquer|d|4||
McLaren|d|4||
Jockey One|s|4||
Give You Glory|h|4||
Vast Shadow|f|4||
Vibur|h|4||
Vesper Libre|f|4579||
Puritan|s|47|47|
Kurale|f|4||
Oleo Script Swash Caps|d|47||
Zen Kurenaido|s|4||
David Libre|f|457||
Gotu|s|4||
Jomhuria|d|4||
Della Respira|f|4||
Arya|s|47||
Zalando Sans SemiExpanded|s|23456789|23456789|wght 200 900 400
Jaldi|s|47||
Kodchasan|s|234567|234567|
Zain|s|234789|34|
Alike|f|4||
Voces|s|4||
Libertinus Math|d|4||
Special Gothic Condensed One|s|4||
Modern Antiqua|d|4||
Metal Mania|d|4||
Asar|f|4||
Baloo Tamma 2|d|45678||wght 400 800 400
Contrail One|d|4||
Quando|f|4||
Rasa|f|34567|34567|wght 300 700 400
Noto Sans Symbols 2|s|4||
Inder|s|4||
Kaisei Opti|f|457||
Sue Ellen Francisco|h|4||
Gurajada|s|4||
Bungee Shade|d|4||
Solway|f|34578||
Sulphur Point|s|347||
Allan|d|47||
Uncial Antiqua|d|4||
Cambay|s|47|47|
Square Peg|h|4||
B612|s|47|47|
Teachers|s|45678|45678|wght 400 800 400
Kalnia|f|1234567||wdth 100 125 100;wght 100 700 400
Noto Serif Thai|f|123456789||wdth 62.5 100 100;wght 100 900 400
Euphoria Script|h|4||
Mr De Haviland|h|4||
Tenali Ramakrishna|s|4||
Coiny|d|4||
Amarante|d|4||
Fuzzy Bubbles|h|47||
Nosifer|d|4||
SUSE|s|123456789|123456789|wght 100 900 400
Averia Sans Libre|d|347|347|
Noto Sans Ethiopic|s|123456789||wdth 62.5 100 100;wght 100 900 400
WindSong|h|45||
Fontdiner Swanky|d|4||
Moon Dance|h|4||
Baloo Chettan 2|d|45678||wght 400 800 400
Artifika|f|4||
Noto Sans Armenian|s|123456789||wdth 62.5 100 100;wght 100 900 400
Martian Mono|m|12345678||wdth 75 112.5 100;wght 100 800 400
Supermercado One|d|4||
Nerko One|h|4||
Codystar|d|34||
Padauk|s|47||
Piazzolla|f|123456789|123456789|opsz 8 30 14;wght 100 900 400
Cutive|f|4||
Short Stack|h|4||
Numans|s|4||
Expletus Sans|d|4567|4567|wght 400 700 400
Montez|h|4||
Antic|s|4||
Delius Unicase|h|47||
Thasadith|s|47|47|
Rosarivo|f|4|4|
Kdam Thmor Pro|s|4||
Special Gothic|s|4567||wdth 75 125 100;wght 400 700 400
Walter Turncoat|h|4||
Bakbak One|d|4||
Arima|d|1234567||wght 100 700 400
Tienne|f|479||
Encode Sans Semi Expanded|s|123456789||
League Script|h|4||
Noto Sans Lao|s|123456789||wdth 62.5 100 100;wght 100 900 400
Bigshot One|d|4||
Prociono|f|4||
Lily Script One|d|4||
Capriola|s|4||
Unkempt|d|47||
Mukta Vaani|s|2345678||
Prosto One|d|4||
Nata Sans|s|123456789||wght 100 900 400
Freehand|d|4||
MonteCarlo|h|4||
Kranky|d|4||
Bilbo Swash Caps|h|4||
Gluten|d|123456789||slnt -13 13 0;wght 100 900 400
Libre Barcode 39 Extended Text|d|4||
Kufam|s|456789|456789|wght 400 900 400
Finger Paint|d|4||
Gamja Flower|h|4||
Anaheim|s|45678||wght 400 800 400
Suranna|f|4||
Atma|d|34567||
Fuggles|h|4||
Freeman|d|4||
Road Rage|d|4||
Cherry Cream Soda|d|4||
Stick No Bills|s|2345678||wght 200 800 400
Mohave|s|34567|34567|wght 300 700 400
Anek Malayalam|s|12345678||wdth 75 125 100;wght 100 800 400
Homenaje|s|4||
Patrick Hand SC|h|4||
Buenard|f|4567||wght 400 700 400
Modak|d|4||
Iceberg|d|4||
Ysabeau Office|s|0.01123456789a|a10.0123456789|wght 1 1000 400
The Girl Next Door|h|4||
Song Myung|f|4||
Cambo|f|4||
Sunflower|s|357||
Amethysta|f|4||
Carattere|h|4||
Aoboshi One|f|4||
Smooch|h|4||
Redressed|h|4||
Asset|d|4||
Birthstone Bounce|h|45||
Mirza|f|4567||
Mako|s|4||
Dynalight|d|4||
Aladin|d|4||
Sedgwick Ave|h|4||
Trade Winds|d|4||
Protest Strike|d|4||
IM Fell Double Pica|f|4|4|
New Rocker|d|4||
Sarpanch|s|456789||
Life Savers|d|478||
Bagel Fat One|d|4||
Moul|d|4||
Zen Antique Soft|f|4||
Sunshiney|h|4||
Balthazar|f|4||
Sansation|s|347|347|
Odibee Sans|d|4||
Molengo|s|4||
Gasoek One|s|4||
BhuTuka Expanded One|f|4||
Charmonman|h|47||
Tiny5|s|4||
Edu SA Beginner|h|4567||wght 400 700 400
Federo|s|4||
Ceviche One|d|4||
Oregano|d|4|4|
Delicious Handrawn|h|4||
Anta|s|4||
Convergence|s|4||
Shanti|s|4||
Borel|h|4||
IM Fell French Canon|f|4|4|
Holtwood One SC|f|4||
Bokor|d|4||
Shippori Antique|s|4||
Mallanna|s|4||
Wittgenstein|f|456789|456789|wght 400 900 400
Noto Sans Bhaiksuki|s|4||
Orelega One|d|4||
Port Lligat Sans|s|4||
Fresca|s|4||
Montaga|f|4||
IM Fell Double Pica SC|f|4||
Imprima|s|4||
Bellota|d|347|347|
Climate Crisis|d|4||YEAR 1979 2050 1979
Meie Script|h|4||
Bruno Ace|d|4||
Science Gothic|s|123456789||CTRS 0 85 0;slnt -10 0 0;wdth 50 200 100;wght 100 900 400
Baumans|d|4||
Scope One|f|4||
Sail|d|4||
Bona Nova|f|47|4|
NTR|s|4||
UnifrakturCook|d|7||
Baloo Paaji 2|d|45678||wght 400 800 400
Doto|s|123456789||ROND 0 100 0;wght 100 900 400
Just Me Again Down Here|h|4||
Madimi One|s|4||
Goblin One|d|4||
Freckle Face|d|4||
Julee|h|4||
Wire One|s|4||
Noto Serif Malayalam|f|123456789||wght 100 900 400
Shojumaru|d|4||
Alike Angular|f|4||
Poor Story|d|4||
Loved by the King|h|4||
Asta Sans|s|345678||wght 300 800 400
Alan Sans|s|3456789||wght 300 900 400
IBM Plex Sans Thai Looped|s|1234567||
Genos|s|123456789|123456789|wght 100 900 400
Headland One|f|4||
Bodoni Moda SC|f|456789|456789|opsz 6 96 11;wght 400 900 400
Darumadrop One|d|4||
Swanky and Moo Moo|h|4||
Rubik Spray Paint|d|4||
Salsa|d|4||
Clicker Script|h|4||
Licorice|h|4||
Bonheur Royale|h|4||
Rubik Bubbles|d|4||
Zhi Mang Xing|h|4||
Sekuya|d|4||
Long Cang|h|4||
Maiden Orange|f|4||
Noto Serif HK|f|23456789||wght 200 900 400
Gayathri|s|147||
Kablammo|d|4||MORF 0 60 0
Train One|d|4||
Rubik Glitch|d|4||
Mochiy Pop P One|s|4||
Ledger|f|4||
Crushed|d|4||
Monofett|m|4||
Alkatra|d|4567||wght 400 700 400
Stack Sans Headline|s|234567||wght 200 700 400
Nova Round|d|4||
Noto Serif Tamil|f|123456789|123456789|wdth 62.5 100 100;wght 100 900 400
Ysabeau SC|s|0.01123456789a||wght 1 1000 400
IM Fell Great Primer|f|4|4|
Sumana|f|47||
Viaoda Libre|d|4||
Karantina|d|347||
Reggae One|d|4||
Wendy One|s|4||
Sour Gummy|s|123456789|123456789|wdth 100 125 100;wght 100 900 400
M PLUS 1 Code|m|1234567||wght 100 700 400
Gupter|f|457||
Galindo|d|4||
Denk One|s|4||
Miltonian Tattoo|d|4||
Harmattan|s|4567||
Eagle Lake|h|4||
Imbue|f|123456789||opsz 10 100 10;wght 100 900 400
IM Fell French Canon SC|f|4||
Mozilla Headline|s|234567||wdth 75 125 100;wght 200 700 400
IM Fell DW Pica SC|f|4||
Henny Penny|d|4||
Kaisei Tokumin|f|4578||
The Nautigal|h|47||
Spicy Rice|d|4||
Sancreek|d|4||
Protest Riot|d|4||
Esteban|f|4||
Grenze|f|123456789|123456789|wght 100 900 400
Delius Swash Caps|h|4||
Smythe|d|4||
Stack Sans Text|s|234567||wght 200 700 400
Nova Flat|d|4||
Medula One|d|4||
Reddit Mono|m|23456789||wght 200 900 400
Gentium Book Plus|f|47|47|
Mina|s|47||
Nokora|s|123456789||wght 100 900 400
Imperial Script|h|4||
Sevillana|d|4||
Anek Tamil|s|12345678||wdth 75 125 100;wght 100 800 400
Duru Sans|s|4||
TASA Orbiter|s|45678||wght 400 800 400
Galada|d|4||
Faculty Glyphic|s|4||
Cherry Swash|d|47||
Manuale|f|345678|345678|wght 300 800 400
Dokdo|d|4||
Luxurious Script|h|4||
Jacques Francois|f|4||
Baloo Bhaina 2|d|45678||wght 400 800 400
Fenix|f|4||
Atomic Age|d|4||
Lemon|d|4||
Mynerve|h|4||
Yomogi|h|4||
Iceland|d|4||
Chicle|d|4||
Comme|s|123456789||wght 100 900 400
Ribeye|d|4||
Orienta|s|4||
Edu TAS Beginner|h|4567||wght 400 700 400
Poltawski Nowy|f|4567|4567|wght 400 700 400
Baloo Tammudu 2|d|45678||wght 400 800 400
Ysabeau|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Habibi|f|4||
Victor Mono|m|1234567|1234567|wght 100 700 400
Nova Oval|d|4||
Gafata|s|4||
Jolly Lodger|d|4||
Truculenta|s|123456789||opsz 12 72 14;wdth 75 125 100;wght 100 900 400
Raleway Dots|d|4||
Nova Slim|d|4||
Trispace|s|12345678||wdth 75 125 100;wght 100 800 400
Waterfall|h|4||
Momo Trust Sans|s|2345678||wght 200 800 400
Nova Cut|d|4||
Chau Philomene One|s|4|4|
Londrina Outline|d|4||
Carme|s|4||
Phudu|d|3456789||wght 300 900 400
Liu Jian Mao Cao|h|4||
Kavoon|d|4||
Peralta|f|4||
Bubbler One|s|4||
Hedvig Letters Sans|s|4||
Overlock SC|d|4||
Moderustic|s|345678||wght 300 800 400
Sura|f|47||
Gugi|d|4||
Miltonian|d|4||
Mozilla Text|s|234567||wght 200 700 400
IM Fell Great Primer SC|f|4||
Ranchers|d|4||
Stick|s|4||
Gemunu Libre|s|2345678||wght 200 800 400
Kulim Park|s|23467|23467|
Varta|s|34567||wght 300 700 400
East Sea Dokdo|h|4||
Miniver|d|4||
Akronim|d|4||
Noto Serif Kannada|f|123456789||wght 100 900 400
Kode Mono|m|4567||wght 400 700 400
Hubot Sans|s|23456789|23456789|wdth 75 125 100;wght 200 900 400
Hi Melody|h|4||
Beau Rivage|h|4||
Kenia|d|4||
Mooli|s|4||
Cute Font|d|4||
Lavishly Yours|h|4||
BIZ UDMincho|f|47||
Caesar Dressing|d|4||
Belgrano|f|4||
Akaya Kanadaka|d|4||
Lovers Quarrel|h|4||
Ruthie|h|4||
Macondo Swash Caps|d|4||
Baskervville SC|f|4567||wght 400 700 400
Timmana|s|4||
Emilys Candy|d|4||
Agdasima|s|47||
Elms Sans|s|123456789|123456789|wght 100 900 400
Bitcount Single|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Zen Tokyo Zoo|d|4||
Libre Barcode 128 Text|d|4||
Cascadia Code|s|234567|234567|wght 200 700 400
Astloch|d|47||
Khmer|s|4||
IBM Plex Sans Devanagari|s|1234567||
Comforter|h|4||
Fascinate|d|4||
Rubik Scribble|d|4||
Gwendolyn|h|47||
Marhey|d|34567||wght 300 700 400
Jaro|s|4||opsz 6 72 14
Playwrite US Trad|h|1234||wght 100 400 400
Tac One|s|4||
Redacted|d|4||
Zilla Slab Highlight|f|47||
Pavanam|s|4||
Englebert|s|4||
Girassol|d|4||
Simonetta|d|49|49|
LXGW WenKai TC|h|347||
Sono|s|2345678||MONO 0 1 1;wght 200 800 400
Badeen Display|d|4||
Engagement|h|4||
Preahvihear|s|4||
Mea Culpa|h|4||
Kavivanar|h|4||
Katibeh|d|4||
Stint Ultra Condensed|f|4||
Noto Sans Buhid|s|4||
Tauri|s|4||
Solitreo|h|4||
Noto Serif Telugu|f|123456789||wght 100 900 400
Suwannaphum|f|13479||
Nova Script|d|4||
Cantora One|s|4||
New Amsterdam|s|4||
Devonshire|h|4||
Margarine|d|4||
Noto Sans Tamil Supplement|s|4||
Story Script|s|4||
Barrio|d|4||
Anek Kannada|s|12345678||wdth 75 125 100;wght 100 800 400
Rationale|s|4||
Noto Music|s|4||
Geom|s|3456789|3456789|wght 300 900 400
Strait|s|4||
Amiri Quran|f|4||
Kotta One|f|4||
Gorditas|d|47||
Seymour One|s|4||
Srisakdi|d|47||
Tiro Devanagari Sanskrit|f|4|4|
Anek Gujarati|s|12345678||wdth 75 125 100;wght 100 800 400
Chocolate Classical Sans|s|4||
Alkalami|f|4||
Mystery Quest|d|4||
Dangrek|d|4||
Stylish|s|4||
Yeon Sung|d|4||
Liter|s|4||
Mate SC|f|4||
Jacquard 12|d|4||
Single Day|d|4||
Joan|f|4||
Sigmar|d|4||
Port Lligat Slab|f|4||
Cactus Classical Serif|f|4||
Glass Antiqua|d|4||
Libertinus Sans|s|47|4|
Edu NSW ACT Cursive|h|4567||wght 400 700 400
Ballet|h|4||opsz 16 72 16
Edu AU VIC WA NT Hand|h|4567||wght 400 700 400
Carrois Gothic SC|s|4||
Lugrasimo|h|4||
Momo Trust Display|s|4||
Akaya Telivigala|d|4||
Passions Conflict|h|4||
Rum Raisin|s|4||
Smokum|d|4||
Stalemate|h|4||
Cagliostro|s|4||
Dorsa|s|4||
Nabla|d|4||EDPT 0 200 100;EHLT 0 24 12
Arbutus|f|4||
Lexend Mega|s|123456789||wght 100 900 400
Noto Sans Mende Kikakui|s|4||
Bilbo|h|4||
Tourney|d|123456789|123456789|wdth 75 125 100;wght 100 900 400
Shippori Antique B1|s|4||
Junge|f|4||
Notable|s|4||
Island Moments|h|4||
Averia Gruesa Libre|d|4||
BBH Bartle|s|4||
Unlock|d|4||
Risque|d|4||
Jomolhari|f|4||
Qahiri|s|4||
Handjet|d|123456789||ELGR 1 2 1;ELSH 0 16 2;wght 100 900 400
Erica One|d|4||
Bungee Hairline|d|4||
Metal|d|4||
Gentium Plus|f|47|47|
Ruluko|s|4||
Braah One|s|4||
Montserrat Underline|s|123456789|123456789|wght 100 900 400
Spirax|d|4||
Siemreap|s|4||
Trykker|f|4||
Stoke|f|34||
Arsenal SC|s|47|47|
Content|d|47||
Noto Serif Tibetan|f|123456789||wght 100 900 400
Underdog|d|4||
Playwrite BR Guides|h|4||
Tillana|d|45678||
Noto Sans Thaana|s|123456789||wght 100 900 400
Paprika|d|4||
Noto Sans Tagalog|s|4||
Geostar Fill|d|4||
Flamenco|d|34||
Romanesco|h|4||
Playwrite DE Grund|h|1234||wght 100 400 400
Ravi Prakash|d|4||
Huninn|s|4||
Noto Sans Canadian Aboriginal|s|123456789||wght 100 900 400
Emblema One|d|4||
Sree Krushnadevaraya|f|4||
Bitcount Grid Double|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Autour One|d|4||
Caramel|h|4||
Kapakana|h|34||wght 300 400 400
Yaldevi|s|234567||wght 200 700 400
SN Pro|s|23456789|23456789|wght 200 900 400
Playwrite DE LA Guides|h|4||
Playwrite IN|h|1234||wght 100 400 400
Playwrite NO|h|1234||wght 100 400 400
Odor Mean Chey|f|4||
Alumni Sans SC|s|123456789|123456789|wght 100 900 400
Manufacturing Consent|d|4||
Playwrite CU|h|1234||wght 100 400 400
National Park|s|2345678||wght 200 800 400
Noto Sans Tai Viet|s|4||
My Soul|h|4||
Noto Sans Coptic|s|4||
Text Me One|s|4||
Stint Ultra Expanded|f|4||
Donegal One|f|4||
Atkinson Hyperlegible Mono|s|2345678|2345678|wght 200 800 400
Ramaraja|f|4||
Elsie Swash Caps|d|49||
Tiro Gurmukhi|f|4|4|
Chilanka|h|4||
Shalimar|h|4||
Vend Sans|s|34567|34567|wght 300 700 400
Almendra Display|d|4||
Butterfly Kids|h|4||
Festive|h|4||
Dai Banna SIL|f|34567|34567|
Jim Nightshade|h|4||
Kaisei HarunoUmi|f|457||
Inika|f|47||
Sonsie One|d|4||
Rubik Moonrocks|d|4||
Piedra|d|4||
Dekko|h|4||
Bitcount Prop Single|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Encode Sans SC|s|123456789||wdth 75 125 100;wght 100 900 400
Kite One|s|4||
Akt|s|123456789||wght 100 900 400
Winky Sans|s|3456789|3456789|wght 300 900 400
Mogra|d|4||
Jersey 20|d|4||
Playpen Sans Arabic|h|12345678||wght 100 800 400
Anek Odia|s|12345678||wdth 75 125 100;wght 100 800 400
Ancizar Serif|f|3456789|3456789|wght 300 900 400
Federant|d|4||
New Tegomin|f|4||
Bonbon|h|4||
Noto Serif Ahom|f|4||
Vibes|d|4||
Yuji Boku|f|4||
Castoro Titling|d|4||
Libre Barcode EAN13 Text|d|4||
Farsan|d|4||
Buda|d|3||
Water Brush|h|4||
Beiruti|s|23456789||wght 200 900 400
Alumni Sans Pinstripe|s|4|4|
Ysabeau Infant|s|0.01123456789a|a10.0123456789|wght 1 1000 400
Texturina|f|123456789|123456789|opsz 12 72 12;wght 100 900 400
Milonga|d|4||
Offside|d|4||
Bpmf Huninn|s|4||
Noto Sans Lao Looped|s|123456789||wdth 62.5 100 100;wght 100 900 400
Comforter Brush|h|4||
Tilt Prism|d|4||XROT -45 45 0;YROT -45 45 0
Updock|h|4||
Monomakh|d|4||
Condiment|h|4||
Playwrite AU NSW|h|1234||wght 100 400 400
Tulpen One|d|4||
Linden Hill|f|4|4|
Playwrite IS|h|1234||wght 100 400 400
Purple Purse|d|4||
Fascinate Inline|d|4||
Koh Santepheap|f|13479||
Big Shoulders Stencil|d|123456789||opsz 10 72 14;wght 100 900 400
Rubik Wet Paint|d|4||
WDXL Lubrifont JP N|s|4||
Send Flowers|h|4||
Ubuntu Sans Mono|m|4567|4567|wght 400 700 400
Gulzar|f|4||
Keania One|d|4||
Noto Sans Samaritan|s|4||
SUSE Mono|s|12345678|12345678|wght 100 800 400
Noto Serif Hebrew|f|123456789||wdth 62.5 100 100;wght 100 900 400
Ancizar Sans|s|123456789a|a123456789|wght 100 1000 400
Praise|h|4||
Diplomata|d|4||
Uchen|f|4||
Luxurious Roman|d|4||
Dhurjati|s|4||
Joti One|d|4||
Inspiration|h|4||
Bacasime Antique|f|4||
Noto Sans Gothic|s|4||
Edu AU VIC WA NT Guides|h|4567||wght 400 700 400
Lexend Tera|s|123456789||wght 100 900 400
Bruno Ace SC|d|4||
Peddana|f|4||
Jacques Francois Shadow|d|4||
Oi|d|4||
Sahitya|f|47||
Lancelot|d|4||
Reem Kufi Fun|s|4567||wght 400 700 400
Passero One|d|4||
Noto Sans Linear A|s|4||
Oldenburg|d|4||
Plaster|d|4||
Bungee Outline|d|4||
Fruktur|d|4|4|
Dr Sugiyama|h|4||
Nuosu SIL|s|4||
Benne|f|4||
Noto Sans Javanese|s|4567||wght 400 700 400
Tiro Devanagari Marathi|f|4|4|
Almendra SC|f|4||
Galdeano|s|4||
Chela One|d|4||
Griffy|d|4||
Noto Serif Armenian|f|123456789||wdth 62.5 100 100;wght 100 900 400
Sirin Stencil|d|4||
Noto Sans Osmanya|s|4||
Playwrite GB S|h|1234|1234|wght 100 400 400
Ewert|d|4||
Playwrite DE SAS Guides|h|4||
Noto Serif Gujarati|f|123456789||wght 100 900 400
Bigelow Rules|d|4||
Noto Serif Ethiopic|f|123456789||wdth 62.5 100 100;wght 100 900 400
Miss Fajardose|h|4||
Fleur De Leah|h|4||
Wellfleet|f|4||
Neonderthaw|h|4||
Intel One Mono|m|34567|34567|wght 300 700 400
Noto Serif Sinhala|f|123456789||wdth 62.5 100 100;wght 100 900 400
Noto Serif Lao|f|123456789||wdth 62.5 100 100;wght 100 900 400
Chiron Hei HK|s|23456789|23456789|wght 200 900 400
Playwrite HR|h|1234||wght 100 400 400
Noto Sans Nag Mundari|s|4567||wght 400 700 400
Betania Patmos|h|4||
Marko One|f|4||
Anek Gurmukhi|s|12345678||wdth 75 125 100;wght 100 800 400
Pliant|s|123456789|123456789|wdth 100 125 100;wght 100 900 400
Londrina Shadow|d|4||
Noto Serif Khmer|f|123456789||wdth 62.5 100 100;wght 100 900 400
Felipa|h|4||
Sixtyfour|m|4||BLED 0 100 0;SCAN -53 100 0
Meera Inimai|s|4||
Noto Sans Sora Sompeng|s|4567||wght 400 700 400
Alyamama|f|3456789||wght 300 900 400
Tiro Tamil|f|4|4|
Libre Barcode 39 Extended|d|4||
Babylonica|h|4||
Aref Ruqaa Ink|f|47||
Playwrite AU SA|h|1234||wght 100 400 400
Konkhmer Sleokchher|d|4||
Matemasie|s|4||
Lakki Reddy|h|4||
Noto Sans Caucasian Albanian|s|4||
Playwrite VN|h|1234||wght 100 400 400
GFS Neohellenic|s|47|47|
Alumni Sans Inline One|d|4|4|
Stalinist One|d|4||
Sofadi One|d|4||
Edu NSW ACT Foundation|h|4567||wght 400 700 400
Twinkle Star|h|4||
Princess Sofia|h|4||
LXGW WenKai Mono TC|m|347||
Slackside One|h|4||
Rhodium Libre|f|4||
Momo Signature|s|4||
Hubballi|s|4||
Orbit|s|4||
Kirang Haerang|d|4||
Diphylleia|f|4||
Chathura|s|13478||
Noto Sans Glagolitic|s|4||
Ranga|d|47||
Butcherman|d|4||
Playwrite VN Guides|h|4||
Cossette Titre|s|47||
Ribeye Marrow|d|4||
Noto Rashi Hebrew|f|123456789||wght 100 900 400
Noto Sans Adlam|s|4567||wght 400 700 400
Noto Serif Dives Akuru|f|4||
Hanalei Fill|d|4||
Noto Serif Myanmar|f|123456789||
Rubik Distressed|d|4||
Sedan|f|4|4|
Grey Qo|h|4||
Rubik Iso|d|4||
Mr Bedfort|h|4||
Revalia|d|4||
Londrina Sketch|d|4||
Iosevka Charon|m|3457|3457|
Reem Kufi Ink|s|4||
Aubrey|d|4||
Gidole|s|4||
Diplomata SC|d|4||
Gidugu|s|4||
Narnoor|s|45678||
Gideon Roman|d|4||
Playwrite IE|h|1234||wght 100 400 400
Iansui|h|4||
Playwrite US Modern|h|1234||wght 100 400 400
Winky Rough|s|3456789|3456789|wght 300 900 400
Kumar One|d|4||
Kalnia Glaze|d|1234567||wdth 100 125 100;wght 100 700 400
Tiro Kannada|f|4|4|
Rubik Pixels|d|4||
Asap Sharp|s|123456789|123456789|wdth 75 125 100;wght 100 900 400
Bahiana|d|4||
Sedan SC|f|4||
Ojuju|s|2345678||wght 200 800 400
Edu VIC WA NT Beginner|h|4567||wght 400 700 400
Jacquarda Bastarda 9|d|4||
Foldit|d|123456789||wght 100 900 400
Shizuru|d|4||
Scoutie Sans|s|2345678|2345678|wght 200 800 400
Lunasima|s|47||
Flavors|d|4||
Jersey 15|d|4||
Caacupe One|d|4||
Grechen Fuemen|h|4||
Snippet|s|4||
Stack Sans Notch|s|234567||wght 200 700 400
WDXL Lubrifont SC|s|4||
Love Light|h|4||
Micro 5|d|4||
BioRhyme Expanded|f|23478||
Tiro Telugu|f|4|4|
Noto Sans Anatolian Hieroglyphs|s|4||
Alumni Sans Collegiate One|s|4|4|
TASA Explorer|s|45678||wght 400 800 400
Ponomar|d|4||
Cossette Texte|s|47||
Noto Sans Tangsa|s|4567||wght 400 700 400
Noto Sans Siddham|s|4||
Valley Sans|s|123456789|123456789|wght 100 900 400
Cause|h|123456789||wght 100 900 400
Noto Sans Syriac|s|123456789||wght 100 900 400
Kedebideri|s|456789||
Playwrite AU TAS|h|1234||wght 100 400 400
Tsukimi Rounded|s|34567||
Molle|h||4|
Triodion|d|4||
Blaka|d|4||
Noto Sans Avestan|s|4||
Trochut|d|47|4|
Big Shoulders Inline|d|123456789||opsz 10 72 14;wght 100 900 400
Kumar One Outline|d|4||
Noto Sans NKo|s|4||
Labrada|f|123456789|123456789|wght 100 900 400
Playpen Sans Hebrew|h|12345678||wght 100 800 400
Miranda Sans|s|4567|4567|wght 400 700 400
Mrs Sheppards|h|4||
Sixtyfour Convergence|m|4||BLED 0 100 0;SCAN -53 100 0;XELA -100 100 0;YELA -100 100 0
Noto Sans Batak|s|4||
Chenla|d|4||
Epunda Sans|s|3456789|3456789|wght 300 900 400
Playwrite HU|h|1234||wght 100 400 400
Noto Sans Cherokee|s|123456789||wght 100 900 400
Moulpali|s|4||
Cascadia Mono|s|234567|234567|wght 200 700 400
Rubik Vinyl|d|4||
Sassy Frass|h|4||
Jacquard 24|d|4||
Bitcount Grid Single|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Playwrite NZ Basic|h|1234||wght 100 400 400
Ga Maamli|d|4||
Grandiflora One|f|4||
Noto Sans Mongolian|s|4||
Kolker Brush|h|4||
Cherish|h|4||
Zen Loop|d|4|4|
Noto Sans Vithkuqi|s|4567||wght 400 700 400
Black And White Picture|d|4||
Noto Sans Pahawh Hmong|s|4||
Noto Sans Cypro Minoan|s|4||
Playwrite AU QLD|h|1234||wght 100 400 400
Noto Sans Shavian|s|4||
Playwrite CA|h|1234||wght 100 400 400
Amarna|s|1234567|1234567|wght 100 700 400
Are You Serious|h|4||
Agu Display|d|4||MORF 0 60 0
Noto Sans Deseret|s|4||
Tai Heritage Pro|f|47||
Flow Block|d|4||
Rubik Puddles|d|4||
Splash|h|4||
BBH Hegarty|s|4||
Ole|h|4||
Danfo|f|4||ELSH 0 100 0
Rubik Glitch Pop|d|4||
Puppies Play|h|4||
Rubik Burned|d|4||
Libertinus Mono|m|4||
Flow Rounded|d|4||
Playpen Sans Thai|h|12345678||wght 100 800 400
Workbench|m|4||BLED 0 100 0;SCAN -53 100 0
Lumanosimo|h|4||
Langar|d|4||
Playwrite MX Guides|h|4||
Noto Traditional Nushu|s|34567||wght 300 700 400
Protest Guerrilla|d|4||
Explora|h|4||
Bungee Tint|d|4||
Kings|h|4||
Noto Sans Balinese|s|4567||wght 400 700 400
Rubik 80s Fade|d|4||
Playwrite PL|h|1234||wght 100 400 400
Noto Sans Lisu|s|4567||wght 400 700 400
Noto Serif Vithkuqi|f|4567||wght 400 700 400
Geist Pixel|d|4||ELSH 0 100 0
Finlandica Text|s|123456789|123456789|wght 100 900 400
Rubik Beastly|d|4||
Redacted Script|d|347||
Noto Sans Syloti Nagri|s|4||
Rubik Gemstones|d|4||
Noto Sans Vai|s|4||
Noto Sans Multani|s|4||
Edu AU VIC WA NT Dots|h|4567||wght 400 700 400
Playwrite DK Loopet|h|1234||wght 100 400 400
Bitcount Single Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Hanalei|d|4||
Noto Sans Marchen|s|4||
Gajraj One|d|4||
Petemoss|h|4||
Estedad|s|123456789||wght 100 900 400
Gveret Levin|h|4||
BBH Bogle|s|4||
Rubik Doodle Triangles|d|4||
Iosevka Charon Mono|m|3457|3457|
Ruwudu|f|4567||
Taprom|d|4||
Playwrite AT|h|1234|1234|wght 100 400 400
Combo|d|4||
WDXL Lubrifont TC|s|4||
Noto Sans Sunuwar|s|4||
UoqMunThenKhung|f|4||
Noto Sans Takri|s|4||
Noto Sans Kaithi|s|4||
BJCree|f|4567||
Noto Sans Old Permic|s|4||
Noto Serif Tangut|f|4||
Estonia|h|4||
Asimovian|s|4||
Chiron Sung HK|f|23456789|23456789|wght 200 900 400
Annapurna SIL|f|47||
Menbere|s|1234567||wght 100 700 400
Coral Pixels|d|4||
Noto Sans Yi|s|4||
Rubik Microbe|d|4||
Noto Sans Carian|s|4||
Noto Sans Old Italic|s|4||
Snowburst One|d|4||
LXGW Marker Gothic|s|4||
Lilex|m|1234567|1234567|wght 100 700 400
Parastoo|f|4567||wght 400 700 400
Playwrite ZA|h|1234||wght 100 400 400
Noto Serif Dogra|f|4||
Tagesschrift|d|4||
Noto Sans Hanunoo|s|4||
Playwrite RO|h|1234||wght 100 400 400
Noto Sans Duployan|s|47||
Rock 3D|d|4||
Noto Sans Old Turkic|s|4||
Bahianita|d|4||
Blaka Hollow|d|4||
Suravaram|f|4||
Syne Tactile|d|4||
Noto Serif Balinese|f|4||
Phetsarath|s|47||
Playwrite DE SAS|h|1234||wght 100 400 400
Moo Lah Lah|d|4||
M PLUS Code Latin|s|1234567||wdth 100 125 100;wght 100 700 400
Geomini|s|2345678||wght 200 800 400
Ruge Boogie|h|4||
Tapestry|h|4||
Linefont|d|123456789a||wdth 25 200 100;wght 4 1000 400
Playwrite DK Uloopet|h|1234||wght 100 400 400
Edu SA Hand|h|4567||wght 400 700 400
Playwrite NL|h|1234||wght 100 400 400
Playwrite FR Moderne|h|1234||wght 100 400 400
Exile|d|4||
Rubik Marker Hatch|d|4||
Noto Serif Yezidi|f|4567||wght 400 700 400
Karla Tamil Inclined|s|47||
Edu QLD Beginner|h|4567||wght 400 700 400
Bitcount|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Libertinus Serif Display|d|4||
Noto Sans Brahmi|s|4||
Playwrite BE VLG|h|1234||wght 100 400 400
Palette Mosaic|d|4||
Savate|s|23456789|23456789|wght 200 900 400
Ingrid Darling|h|4||
Noto Sans Runic|s|4||
Playpen Sans Deva|h|12345678||wght 100 800 400
Rubik Broken Fax|d|4||
Moirai One|d|4||
Hind Mysuru|s|34567||
Noto Serif Toto|f|4567||wght 400 700 400
Playwrite GB J|h|1234|1234|wght 100 400 400
Noto Sans Miao|s|4||
Noto Sans Egyptian Hieroglyphs|s|4||
Playwrite AR|h|1234||wght 100 400 400
Geostar|d|4||
Yuyu|h|4||
Noto Sans Nandinagari|s|4||
Bytesized|s|4||
Epunda Slab|f|3456789|3456789|wght 300 900 400
Rubik Maps|d|4||
Hibur Mono|m|4||
Sirivennela|s|4||
Tirra|s|456789||
Noto Sans Osage|s|4||
Rubik Maze|d|4||
Noto Sans Tifinagh|s|4||
Noto Serif Gurmukhi|f|123456789||wght 100 900 400
Playwrite IT Moderna|h|1234||wght 100 400 400
Noto Sans Bamum|s|4567||wght 400 700 400
Mingzat|s|4||
Noto Sans Cypriot|s|4||
Playwrite ES|h|1234||wght 100 400 400
Lisu Bosa|f|23456789|23456789|
Chokokutai|d|4||
Playwrite PT|h|1234||wght 100 400 400
Playwrite MX|h|1234||wght 100 400 400
Sankofa Display|s|4||
Noto Serif Oriya|f|4567||wght 400 700 400
Montenegrin Gothic One|f|4||
Noto Sans Grantha|s|4||
Alien Block|d|4||
Noto Sans Old Hungarian|s|4||
Noto Sans Old Persian|s|4||
Noto Sans Adlam Unjoined|s|4567||wght 400 700 400
Playwrite HR Lijeva|h|1234||wght 100 400 400
Noto Sans Soyombo|s|4||
Ponnala|d|4||
Noto Sans Syriac Eastern|s|123456789||wght 100 900 400
Namdhinggo|f|45678||
Datatype|m|123456789||wdth 50 150 100;wght 100 900 400
Edu AU VIC WA NT Pre|h|4567||wght 400 700 400
Noto Sans Mandaic|s|4||
Jaini Purva|d|4||
Shafarik|d|4||
Karla Tamil Upright|s|47||
Allkin|d|4||
Noto Sans Newa|s|4||
Noto Sans Lydian|s|4||
Yuyu Short|h|4||
Noto Sans Indic Siyaq Numbers|s|4||
Noto Serif Khitan Small Script|f|4||
Rubik Lines|d|4||
Jaini|d|4||
Jacquard 12 Charted|d|4||
Noto Znamenny Musical Notation|s|4||
Bpmf Zihi Kai Std|s|4||
Noto Sans Medefaidrin|s|4567||wght 400 700 400
Noto Serif Todhri|f|4||
Warnes|d|4||
Noto Sans Tai Le|s|4||
Noto Serif Ottoman Siyaq|f|4||
Playwrite NZ|h|1234||wght 100 400 400
Noto Sans Mahajani|s|4||
Noto Sans Sundanese|s|4567||wght 400 700 400
Noto Sans Elbasan|s|4||
Blaka Ink|d|4||
Bitcount Prop Double Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Edu NSW ACT Hand Pre|h|4567||wght 400 700 400
Saira Stencil|d|123456789|123456789|wdth 50 125 100;wght 100 900 400
Rubik Storm|d|4||
Wavefont|d|123456789a||ROND 0 100 100;YELA -100 100 -100;wght 4 1000 400
Noto Serif NP Hmong|f|4567||wght 400 700 400
Noto Sans Pau Cin Hau|s|4||
Yuji Hentaigana Akari|h|4||
Noto Sans Nabataean|s|4||
Bitcount Grid Single Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Playwrite AU SA Guides|h|4||
Noto Sans Cham|s|123456789||wght 100 900 400
Playwrite SK|h|1234||wght 100 400 400
Noto Sans Old North Arabian|s|4||
Maname|f|4||
Tuffy|s|47|47|
Noto Sans Meroitic|s|4||
Playwrite CU Guides|h|4||
Matangi|s|3456789||wght 300 900 400
Noto Sans Wancho|s|4||
Edu VIC WA NT Hand|h|4567||wght 400 700 400
Playwrite NG Modern|h|1234||wght 100 400 400
Playwrite AU VIC|h|1234||wght 100 400 400
Noto Sans Cuneiform|s|4||
Playwrite CZ|h|1234||wght 100 400 400
Kay Pho Du|f|4567||
Bitcount Prop Double|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;slnt -8 0 0;wght 100 900 400
Noto Serif Makasar|f|4||
Libertinus Keyboard|d|4||
Noto Sans Inscriptional Parthian|s|4||
Noto Sans Limbu|s|4||
Noto Sans Hanifi Rohingya|s|4567||wght 400 700 400
Playwrite DE LA|h|1234||wght 100 400 400
Noto Sans Palmyrene|s|4||
Noto Sans Khojki|s|4||
Noto Sans Imperial Aramaic|s|4||
Noto Sans NKo Unjoined|s|4567||wght 400 700 400
Finlandica Headline|s|123456789|123456789|wght 100 900 400
Edu AU VIC WA NT Arrows|h|4567||wght 400 700 400
Strichpunkt Sans|s|456789||wdth 100 200 100;wght 400 900 400
Bpmf Iansui|h|4||
Noto Sans Inscriptional Pahlavi|s|4||
Playwrite CO Guides|h|4||
Noto Sans Mayan Numerals|s|4||
Noto Serif Hentaigana|f|23456789||wght 200 900 400
Noto Sans Kawi|s|4567||wght 400 700 400
Padyakke Expanded One|f|4||
Jersey 10 Charted|d|4||
Noto Sans Buginese|s|4||
Playwrite TZ|h|1234||wght 100 400 400
Bitcount Prop Single Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Noto Sans SignWriting|s|4||
Playwrite CO|h|1234||wght 100 400 400
Noto Sans Old South Arabian|s|4||
Noto Sans Khudawadi|s|4||
Playwrite BE WAL|h|1234||wght 100 400 400
Playwrite US Trad Guides|h|4||
Bitcount Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Noto Sans Sogdian|s|4||
Noto Serif Grantha|f|4||
Noto Sans Sharada|s|4||
Bitcount Grid Double Ink|d|123456789||CRSV 0 1 0.5;ELSH 0 100 0;ELXP 0 100 0;SZP1 0 100 0;SZP2 0 100 0;XPN1 -100 100 0;XPN2 -100 100 0;YPN1 -100 100 0;YPN2 -100 100 0;slnt -8 0 0;wght 100 900 400
Noto Sans Zanabazar Square|s|4||
Noto Sans Rejang|s|4||
Noto Sans Chakma|s|4||
Pochaevsk|d|4||
Noto Sans Phoenician|s|4||
Idiqlat|f|234||
Betania Patmos In|h|4||
Noto Sans Hatran|s|4||
Betania Patmos In GDL|h|4||
Noto Sans Linear B|s|4||
Jacquard 24 Charted|d|4||
Playwrite ID|h|1234||wght 100 400 400
Playwrite CL|h|1234||wght 100 400 400
Noto Serif Old Uyghur|f|4||
Jersey 15 Charted|d|4||
Jersey 25 Charted|d|4||
Noto Sans Tagbanwa|s|4||
Noto Sans Elymaic|s|4||
Playwrite PE|h|1234||wght 100 400 400
Playwrite AU VIC Guides|h|4||
Playwrite GB J Guides|h|4|4|
Noto Sans Ugaritic|s|4||
Edu QLD Hand|h|4567||wght 400 700 400
Betania Patmos GDL|h|4||
Micro 5 Charted|d|4||
Noto Sans Tai Tham|s|4567||wght 400 700 400
Noto Sans Tirhuta|s|4||
Noto Sans New Tai Lue|s|4567||wght 400 700 400
Noto Sans Saurashtra|s|4||
Playwrite ES Deco|h|1234||wght 100 400 400
Playwrite BR|h|1234||wght 100 400 400
Edu VIC WA NT Hand Pre|h|4567||wght 400 700 400
Noto Sans Mro|s|4||
Noto Sans Ogham|s|4||
Noto Sans Bassa Vah|s|4567||wght 400 700 400
Jersey 20 Charted|d|4||
Noto Sans Psalter Pahlavi|s|4||
Noto Sans PhagsPa|s|4||
Yarndings 20 Charted|d|4||
Noto Sans Masaram Gondi|s|4||
Kanchenjunga|s|4567||
Yuji Hentaigana Akebono|h|4||
Noto Sans Syriac Western|s|123456789||wght 100 900 400
Noto Sans Chorasmian|s|4||
Noto Sans Nushu|s|4||
Noto Sans Gunjala Gondi|s|4567||wght 400 700 400
Noto Sans Manichaean|s|4||
Noto Sans Kharoshthi|s|4||
Noto Sans Modi|s|4||
Playwrite NZ Guides|h|4||
Playwrite IT Trad|h|1234||wght 100 400 400
Yarndings 20|d|4||
Playwrite IN Guides|h|4||
Noto Sans Lepcha|s|4||
Playwrite FR Trad|h|1234||wght 100 400 400
Noto Sans Old Sogdian|s|4||
Noto Sans Kayah Li|s|4567||wght 400 700 400
Playwrite PL Guides|h|4||
Jacquarda Bastarda 9 Charted|d|4||
Playwrite PT Guides|h|4||
Yarndings 12|d|4||
Playwrite DE VA|h|1234||wght 100 400 400
Playwrite DE Grund Guides|h|4||
Noto Sans Lycian|s|4||
Playwrite PE Guides|h|4||
Playwrite GB S Guides|h|4|4|
Playwrite NZ Basic Guides|h|4||
Playwrite AR Guides|h|4||
Playwrite TZ Guides|h|4||
Ramsina|f|4||
Yarndings 12 Charted|d|4||
Playwrite BE WAL Guides|h|4||
Playwrite HU Guides|h|4||
Playwrite DK Uloopet Guides|h|4||
Playwrite DE VA Guides|h|4||
Playwrite ES Deco Guides|h|4||
Playwrite IT Moderna Guides|h|4||
Playwrite IE Guides|h|4||
Playwrite AU NSW Guides|h|4||
Playwrite AU TAS Guides|h|4||
Playwrite FR Moderne Guides|h|4||
Playwrite IT Trad Guides|h|4||
Playwrite FR Trad Guides|h|4||
Playwrite AU QLD Guides|h|4||
Playwrite US Modern Guides|h|4||
Playwrite DK Loopet Guides|h|4||
Playwrite AT Guides|h|4|4|
Playwrite ZA Guides|h|4||
Playwrite IS Guides|h|4||
Playwrite ES Guides|h|4||
Playwrite NL Guides|h|4||
Playwrite HR Lijeva Guides|h|4||
Playwrite ID Guides|h|4||
Playwrite CL Guides|h|4||
Playwrite SK Guides|h|4||
Playwrite HR Guides|h|4||
Playwrite NG Modern Guides|h|4||
Playwrite CA Guides|h|4||
Playwrite NO Guides|h|4||
Playwrite BE VLG Guides|h|4||
Playwrite RO Guides|h|4||
Playwrite CZ Guides|h|4||`;
